# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlExecForward < Formula
  desc "A kubectl plugin to run exec hooks exposed by a Kubernetes pod around a port-forward action."
  homepage "https://github.com/takescoop/kubectl-exec-forward"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TakeScoop/kubectl-exec-forward/releases/download/v0.0.1/kubectl-exec-forward_0.0.1_darwin_amd64.tar.gz"
      sha256 "240744653d81aaa220d76bb832eb5830f5cfbf07151c9e0c7ac210903afb9e52"

      def install
        bin.install "kubectl-exec_forward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TakeScoop/kubectl-exec-forward/releases/download/v0.0.1/kubectl-exec-forward_0.0.1_darwin_arm64.tar.gz"
      sha256 "76ec03b27be20e3d5bea9d444eb2905a9acb815bef06d704cbc45f7c89507187"

      def install
        bin.install "kubectl-exec_forward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TakeScoop/kubectl-exec-forward/releases/download/v0.0.1/kubectl-exec-forward_0.0.1_linux_arm64.tar.gz"
      sha256 "78ae366f42e1ba7c15c02c19a739d9ea2c28a08da2e7213aa03d6a53ab31c0f6"

      def install
        bin.install "kubectl-exec_forward"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TakeScoop/kubectl-exec-forward/releases/download/v0.0.1/kubectl-exec-forward_0.0.1_linux_amd64.tar.gz"
      sha256 "a512cdbe7207f1818986bab71e86cc1001634e21b60b74d22542b82cd44a5ec0"

      def install
        bin.install "kubectl-exec_forward"
      end
    end
  end
end
