_extends: .github
repository:
  name: kubectl-service-port-forward
  description: A kubectl plugin used to port forward to a Kubernetes Service and run commands listed in the Service's annotations
  topics: kubernetes, kubectl
  allow_auto_merge: true
branches:
  - name: master
    protection:
      required_status_checks:
        contexts:
          - default
