_extends: .github
repository:
  name: kubectl-port-forward-hooks
  description: A kubectl plugin to execute hooks exposed by a Kubernetes resource around a port-forwarding action.
  topics: kubernetes, kubectl
  allow_auto_merge: true
branches:
  - name: master
    protection:
      required_status_checks:
        contexts:
          - default
