_extends: .github
repository:
  name: kubectl-exec-forward
  description: A kubectl plugin to run exec hooks exposed by a Kubernetes pod around a port-forward action.
  topics: kubernetes, kubectl
  allow_auto_merge: true
  private: false
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null