run:
  deadline: 15m
linters:
  enable-all: true
  disable:
    - interfacer
    - testpackage
    - goerr113
    - scopelint
    - gomnd
    - exhaustivestruct
    - lll
    - funlen
    - wrapcheck
    - paralleltest
    - cyclop
    - maligned
    - stylecheck
    - varnamelen
    - ireturn
issues:
  exclude-use-default: false
