
builds:
  - binary: kubectl-exec_forward
brews:
  - tap:
      owner: takescoop
      name: kubectl-exec-forward
    folder: HomebrewFormula
    homepage: https://github.com/takescoop/kubectl-exec-forward
    description: A kubectl plugin to run exec hooks exposed by a Kubernetes pod around a port-forward action.
