on:
  push:
    tags:
      - 'v*'
name: Release
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Generate token
        id: token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.HOMEBREW_APP_ID }}
          private_key: ${{ secrets.HOMEBREW_PRIVATE_KEY }}
          repository: takescoop/homebrew-formulas
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
