name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Test
        run: go test -race -v ./...
